//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SearcherCore.net.bing.api {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BingPortBinding", Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class BingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SearchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BingService() {
            this.Url = global::SearcherCore.Properties.Settings.Default.SearcherCore_net_bing_api_BingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchCompletedEventHandler SearchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/LiveSearch/2008/03/Search/Search", RequestElementName="SearchRequest", RequestNamespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search", ResponseNamespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("parameters")]
        public SearchResponse Search(SearchRequest parameters) {
            object[] results = this.Invoke("Search", new object[] {
                        parameters});
            return ((SearchResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SearchAsync(SearchRequest parameters) {
            this.SearchAsync(parameters, null);
        }
        
        /// <remarks/>
        public void SearchAsync(SearchRequest parameters, object userState) {
            if ((this.SearchOperationCompleted == null)) {
                this.SearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchOperationCompleted);
            }
            this.InvokeAsync("Search", new object[] {
                        parameters}, this.SearchOperationCompleted, userState);
        }
        
        private void OnSearchOperationCompleted(object arg) {
            if ((this.SearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCompleted(this, new SearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class SearchRequest {
        
        private string versionField;
        
        private string marketField;
        
        private string uILanguageField;
        
        private string queryField;
        
        private string appIdField;
        
        private AdultOption adultField;
        
        private bool adultFieldSpecified;
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private double longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private double radiusField;
        
        private bool radiusFieldSpecified;
        
        private SearchOption[] optionsField;
        
        private SourceType[] sourcesField;
        
        private WebRequest webField;
        
        private ImageRequest imageField;
        
        private PhonebookRequest phonebookField;
        
        private VideoRequest videoField;
        
        private NewsRequest newsField;
        
        private MobileWebRequest mobileWebField;
        
        private TranslationRequest translationField;
        
        public SearchRequest() {
            this.versionField = "2.2";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("2.2")]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string Market {
            get {
                return this.marketField;
            }
            set {
                this.marketField = value;
            }
        }
        
        /// <remarks/>
        public string UILanguage {
            get {
                return this.uILanguageField;
            }
            set {
                this.uILanguageField = value;
            }
        }
        
        /// <remarks/>
        public string Query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        public string AppId {
            get {
                return this.appIdField;
            }
            set {
                this.appIdField = value;
            }
        }
        
        /// <remarks/>
        public AdultOption Adult {
            get {
                return this.adultField;
            }
            set {
                this.adultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdultSpecified {
            get {
                return this.adultFieldSpecified;
            }
            set {
                this.adultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RadiusSpecified {
            get {
                return this.radiusFieldSpecified;
            }
            set {
                this.radiusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public SearchOption[] Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        public SourceType[] Sources {
            get {
                return this.sourcesField;
            }
            set {
                this.sourcesField = value;
            }
        }
        
        /// <remarks/>
        public WebRequest Web {
            get {
                return this.webField;
            }
            set {
                this.webField = value;
            }
        }
        
        /// <remarks/>
        public ImageRequest Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        public PhonebookRequest Phonebook {
            get {
                return this.phonebookField;
            }
            set {
                this.phonebookField = value;
            }
        }
        
        /// <remarks/>
        public VideoRequest Video {
            get {
                return this.videoField;
            }
            set {
                this.videoField = value;
            }
        }
        
        /// <remarks/>
        public NewsRequest News {
            get {
                return this.newsField;
            }
            set {
                this.newsField = value;
            }
        }
        
        /// <remarks/>
        public MobileWebRequest MobileWeb {
            get {
                return this.mobileWebField;
            }
            set {
                this.mobileWebField = value;
            }
        }
        
        /// <remarks/>
        public TranslationRequest Translation {
            get {
                return this.translationField;
            }
            set {
                this.translationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum AdultOption {
        
        /// <remarks/>
        Off,
        
        /// <remarks/>
        Moderate,
        
        /// <remarks/>
        Strict,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum SearchOption {
        
        /// <remarks/>
        DisableLocationDetection,
        
        /// <remarks/>
        EnableHighlighting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum SourceType {
        
        /// <remarks/>
        Spell,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        Image,
        
        /// <remarks/>
        RelatedSearch,
        
        /// <remarks/>
        Phonebook,
        
        /// <remarks/>
        Showtimes,
        
        /// <remarks/>
        Weather,
        
        /// <remarks/>
        Video,
        
        /// <remarks/>
        Ad,
        
        /// <remarks/>
        XRank,
        
        /// <remarks/>
        InstantAnswer,
        
        /// <remarks/>
        News,
        
        /// <remarks/>
        QueryLocation,
        
        /// <remarks/>
        MobileWeb,
        
        /// <remarks/>
        Translation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class WebRequest {
        
        private uint offsetField;
        
        private bool offsetFieldSpecified;
        
        private uint countField;
        
        private bool countFieldSpecified;
        
        private string fileTypeField;
        
        private WebSearchOption[] optionsField;
        
        private string[] searchTagsField;
        
        /// <remarks/>
        public uint Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        public WebSearchOption[] Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] SearchTags {
            get {
                return this.searchTagsField;
            }
            set {
                this.searchTagsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum WebSearchOption {
        
        /// <remarks/>
        DisableHostCollapsing,
        
        /// <remarks/>
        DisableQueryAlterations,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class Error {
        
        private uint codeField;
        
        private bool codeFieldSpecified;
        
        private string messageField;
        
        private string parameterField;
        
        private string valueField;
        
        private string helpUrlField;
        
        private string sourceTypeField;
        
        private uint sourceTypeErrorCodeField;
        
        private bool sourceTypeErrorCodeFieldSpecified;
        
        /// <remarks/>
        public uint Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string HelpUrl {
            get {
                return this.helpUrlField;
            }
            set {
                this.helpUrlField = value;
            }
        }
        
        /// <remarks/>
        public string SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
            }
        }
        
        /// <remarks/>
        public uint SourceTypeErrorCode {
            get {
                return this.sourceTypeErrorCodeField;
            }
            set {
                this.sourceTypeErrorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceTypeErrorCodeSpecified {
            get {
                return this.sourceTypeErrorCodeFieldSpecified;
            }
            set {
                this.sourceTypeErrorCodeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class TranslationResult {
        
        private string translatedTermField;
        
        /// <remarks/>
        public string TranslatedTerm {
            get {
                return this.translatedTermField;
            }
            set {
                this.translatedTermField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class TranslationResponse {
        
        private TranslationResult[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TranslationResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class MobileWebResult {
        
        private string titleField;
        
        private string descriptionField;
        
        private string urlField;
        
        private string displayUrlField;
        
        private string dateTimeField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayUrl {
            get {
                return this.displayUrlField;
            }
            set {
                this.displayUrlField = value;
            }
        }
        
        /// <remarks/>
        public string DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class MobileWebResponse {
        
        private uint totalField;
        
        private bool totalFieldSpecified;
        
        private uint offsetField;
        
        private bool offsetFieldSpecified;
        
        private MobileWebResult[] resultsField;
        
        /// <remarks/>
        public uint Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MobileWebResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class NewsArticle {
        
        private string titleField;
        
        private string urlField;
        
        private string sourceField;
        
        private string snippetField;
        
        private string dateField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string Snippet {
            get {
                return this.snippetField;
            }
            set {
                this.snippetField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class NewsCollection {
        
        private string nameField;
        
        private NewsArticle[] newsArticlesField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NewsArticle[] NewsArticles {
            get {
                return this.newsArticlesField;
            }
            set {
                this.newsArticlesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class NewsResult {
        
        private string titleField;
        
        private string urlField;
        
        private string sourceField;
        
        private string snippetField;
        
        private string dateField;
        
        private uint breakingNewsField;
        
        private bool breakingNewsFieldSpecified;
        
        private NewsCollection[] newsCollectionsField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string Snippet {
            get {
                return this.snippetField;
            }
            set {
                this.snippetField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public uint BreakingNews {
            get {
                return this.breakingNewsField;
            }
            set {
                this.breakingNewsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BreakingNewsSpecified {
            get {
                return this.breakingNewsFieldSpecified;
            }
            set {
                this.breakingNewsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NewsCollection[] NewsCollections {
            get {
                return this.newsCollectionsField;
            }
            set {
                this.newsCollectionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class NewsRelatedSearch {
        
        private string titleField;
        
        private string urlField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class NewsResponse {
        
        private uint totalField;
        
        private bool totalFieldSpecified;
        
        private uint offsetField;
        
        private bool offsetFieldSpecified;
        
        private NewsRelatedSearch[] relatedSearchesField;
        
        private NewsResult[] resultsField;
        
        /// <remarks/>
        public uint Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NewsRelatedSearch[] RelatedSearches {
            get {
                return this.relatedSearchesField;
            }
            set {
                this.relatedSearchesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NewsResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class InstantAnswerResult {
        
        private string contentTypeField;
        
        private string titleField;
        
        private string clickThroughUrlField;
        
        private string urlField;
        
        private string attributionField;
        
        private string instantAnswerSpecificDataField;
        
        /// <remarks/>
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string ClickThroughUrl {
            get {
                return this.clickThroughUrlField;
            }
            set {
                this.clickThroughUrlField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string Attribution {
            get {
                return this.attributionField;
            }
            set {
                this.attributionField = value;
            }
        }
        
        /// <remarks/>
        public string InstantAnswerSpecificData {
            get {
                return this.instantAnswerSpecificDataField;
            }
            set {
                this.instantAnswerSpecificDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class InstantAnswerResponse {
        
        private InstantAnswerResult[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public InstantAnswerResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class VideoResult {
        
        private string titleField;
        
        private string playUrlField;
        
        private string sourceTitleField;
        
        private uint runTimeField;
        
        private bool runTimeFieldSpecified;
        
        private string clickThroughPageUrlField;
        
        private Thumbnail staticThumbnailField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string PlayUrl {
            get {
                return this.playUrlField;
            }
            set {
                this.playUrlField = value;
            }
        }
        
        /// <remarks/>
        public string SourceTitle {
            get {
                return this.sourceTitleField;
            }
            set {
                this.sourceTitleField = value;
            }
        }
        
        /// <remarks/>
        public uint RunTime {
            get {
                return this.runTimeField;
            }
            set {
                this.runTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RunTimeSpecified {
            get {
                return this.runTimeFieldSpecified;
            }
            set {
                this.runTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ClickThroughPageUrl {
            get {
                return this.clickThroughPageUrlField;
            }
            set {
                this.clickThroughPageUrlField = value;
            }
        }
        
        /// <remarks/>
        public Thumbnail StaticThumbnail {
            get {
                return this.staticThumbnailField;
            }
            set {
                this.staticThumbnailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class Thumbnail {
        
        private string urlField;
        
        private string contentTypeField;
        
        private uint widthField;
        
        private bool widthFieldSpecified;
        
        private uint heightField;
        
        private bool heightFieldSpecified;
        
        private uint fileSizeField;
        
        private bool fileSizeFieldSpecified;
        
        private uint runTimeField;
        
        private bool runTimeFieldSpecified;
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        public uint Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileSizeSpecified {
            get {
                return this.fileSizeFieldSpecified;
            }
            set {
                this.fileSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint RunTime {
            get {
                return this.runTimeField;
            }
            set {
                this.runTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RunTimeSpecified {
            get {
                return this.runTimeFieldSpecified;
            }
            set {
                this.runTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class VideoResponse {
        
        private uint totalField;
        
        private bool totalFieldSpecified;
        
        private uint offsetField;
        
        private bool offsetFieldSpecified;
        
        private VideoResult[] resultsField;
        
        /// <remarks/>
        public uint Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public VideoResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class PhonebookResult {
        
        private string titleField;
        
        private string urlField;
        
        private string businessField;
        
        private string phoneNumberField;
        
        private string addressField;
        
        private string cityField;
        
        private string stateOrProvinceField;
        
        private string countryOrRegionField;
        
        private string postalCodeField;
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private double longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private string uniqueIdField;
        
        private string businessUrlField;
        
        private double userRatingField;
        
        private bool userRatingFieldSpecified;
        
        private uint reviewCountField;
        
        private bool reviewCountFieldSpecified;
        
        private string displayUrlField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string Business {
            get {
                return this.businessField;
            }
            set {
                this.businessField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateOrProvince {
            get {
                return this.stateOrProvinceField;
            }
            set {
                this.stateOrProvinceField = value;
            }
        }
        
        /// <remarks/>
        public string CountryOrRegion {
            get {
                return this.countryOrRegionField;
            }
            set {
                this.countryOrRegionField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string UniqueId {
            get {
                return this.uniqueIdField;
            }
            set {
                this.uniqueIdField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessUrl {
            get {
                return this.businessUrlField;
            }
            set {
                this.businessUrlField = value;
            }
        }
        
        /// <remarks/>
        public double UserRating {
            get {
                return this.userRatingField;
            }
            set {
                this.userRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserRatingSpecified {
            get {
                return this.userRatingFieldSpecified;
            }
            set {
                this.userRatingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint ReviewCount {
            get {
                return this.reviewCountField;
            }
            set {
                this.reviewCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReviewCountSpecified {
            get {
                return this.reviewCountFieldSpecified;
            }
            set {
                this.reviewCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DisplayUrl {
            get {
                return this.displayUrlField;
            }
            set {
                this.displayUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class PhonebookResponse {
        
        private uint totalField;
        
        private bool totalFieldSpecified;
        
        private uint offsetField;
        
        private bool offsetFieldSpecified;
        
        private string localSerpUrlField;
        
        private string titleField;
        
        private PhonebookResult[] resultsField;
        
        /// <remarks/>
        public uint Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string LocalSerpUrl {
            get {
                return this.localSerpUrlField;
            }
            set {
                this.localSerpUrlField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PhonebookResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class RelatedSearchResult {
        
        private string titleField;
        
        private string urlField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class RelatedSearchResponse {
        
        private RelatedSearchResult[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RelatedSearchResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class ImageResult {
        
        private string titleField;
        
        private string mediaUrlField;
        
        private string urlField;
        
        private string displayUrlField;
        
        private uint widthField;
        
        private bool widthFieldSpecified;
        
        private uint heightField;
        
        private bool heightFieldSpecified;
        
        private uint fileSizeField;
        
        private bool fileSizeFieldSpecified;
        
        private string contentTypeField;
        
        private Thumbnail thumbnailField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string MediaUrl {
            get {
                return this.mediaUrlField;
            }
            set {
                this.mediaUrlField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayUrl {
            get {
                return this.displayUrlField;
            }
            set {
                this.displayUrlField = value;
            }
        }
        
        /// <remarks/>
        public uint Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileSizeSpecified {
            get {
                return this.fileSizeFieldSpecified;
            }
            set {
                this.fileSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        public Thumbnail Thumbnail {
            get {
                return this.thumbnailField;
            }
            set {
                this.thumbnailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class ImageResponse {
        
        private uint totalField;
        
        private bool totalFieldSpecified;
        
        private uint offsetField;
        
        private bool offsetFieldSpecified;
        
        private ImageResult[] resultsField;
        
        /// <remarks/>
        public uint Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ImageResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class DeepLink {
        
        private string titleField;
        
        private string urlField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class WebSearchTag {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class WebResult {
        
        private string titleField;
        
        private string descriptionField;
        
        private string urlField;
        
        private string cacheUrlField;
        
        private string displayUrlField;
        
        private string dateTimeField;
        
        private WebSearchTag[] searchTagsField;
        
        private DeepLink[] deepLinksField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string CacheUrl {
            get {
                return this.cacheUrlField;
            }
            set {
                this.cacheUrlField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayUrl {
            get {
                return this.displayUrlField;
            }
            set {
                this.displayUrlField = value;
            }
        }
        
        /// <remarks/>
        public string DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WebSearchTag[] SearchTags {
            get {
                return this.searchTagsField;
            }
            set {
                this.searchTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DeepLink[] DeepLinks {
            get {
                return this.deepLinksField;
            }
            set {
                this.deepLinksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class WebResponse {
        
        private uint totalField;
        
        private bool totalFieldSpecified;
        
        private uint offsetField;
        
        private bool offsetFieldSpecified;
        
        private WebResult[] resultsField;
        
        /// <remarks/>
        public uint Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WebResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class SpellResult {
        
        private string valueField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class SpellResponse {
        
        private uint totalField;
        
        private bool totalFieldSpecified;
        
        private SpellResult[] resultsField;
        
        /// <remarks/>
        public uint Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SpellResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class Query {
        
        private string searchTermsField;
        
        private string alteredQueryField;
        
        private string alterationOverrideQueryField;
        
        /// <remarks/>
        public string SearchTerms {
            get {
                return this.searchTermsField;
            }
            set {
                this.searchTermsField = value;
            }
        }
        
        /// <remarks/>
        public string AlteredQuery {
            get {
                return this.alteredQueryField;
            }
            set {
                this.alteredQueryField = value;
            }
        }
        
        /// <remarks/>
        public string AlterationOverrideQuery {
            get {
                return this.alterationOverrideQueryField;
            }
            set {
                this.alterationOverrideQueryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class SearchResponse {
        
        private string versionField;
        
        private Query queryField;
        
        private SpellResponse spellField;
        
        private WebResponse webField;
        
        private ImageResponse imageField;
        
        private RelatedSearchResponse relatedSearchField;
        
        private PhonebookResponse phonebookField;
        
        private VideoResponse videoField;
        
        private InstantAnswerResponse instantAnswerField;
        
        private NewsResponse newsField;
        
        private MobileWebResponse mobileWebField;
        
        private TranslationResponse translationField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public Query Query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        public SpellResponse Spell {
            get {
                return this.spellField;
            }
            set {
                this.spellField = value;
            }
        }
        
        /// <remarks/>
        public WebResponse Web {
            get {
                return this.webField;
            }
            set {
                this.webField = value;
            }
        }
        
        /// <remarks/>
        public ImageResponse Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        public RelatedSearchResponse RelatedSearch {
            get {
                return this.relatedSearchField;
            }
            set {
                this.relatedSearchField = value;
            }
        }
        
        /// <remarks/>
        public PhonebookResponse Phonebook {
            get {
                return this.phonebookField;
            }
            set {
                this.phonebookField = value;
            }
        }
        
        /// <remarks/>
        public VideoResponse Video {
            get {
                return this.videoField;
            }
            set {
                this.videoField = value;
            }
        }
        
        /// <remarks/>
        public InstantAnswerResponse InstantAnswer {
            get {
                return this.instantAnswerField;
            }
            set {
                this.instantAnswerField = value;
            }
        }
        
        /// <remarks/>
        public NewsResponse News {
            get {
                return this.newsField;
            }
            set {
                this.newsField = value;
            }
        }
        
        /// <remarks/>
        public MobileWebResponse MobileWeb {
            get {
                return this.mobileWebField;
            }
            set {
                this.mobileWebField = value;
            }
        }
        
        /// <remarks/>
        public TranslationResponse Translation {
            get {
                return this.translationField;
            }
            set {
                this.translationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class TranslationRequest {
        
        private string sourceLanguageField;
        
        private string targetLanguageField;
        
        /// <remarks/>
        public string SourceLanguage {
            get {
                return this.sourceLanguageField;
            }
            set {
                this.sourceLanguageField = value;
            }
        }
        
        /// <remarks/>
        public string TargetLanguage {
            get {
                return this.targetLanguageField;
            }
            set {
                this.targetLanguageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class MobileWebRequest {
        
        private uint offsetField;
        
        private bool offsetFieldSpecified;
        
        private uint countField;
        
        private bool countFieldSpecified;
        
        private MobileWebSearchOption[] optionsField;
        
        /// <remarks/>
        public uint Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public MobileWebSearchOption[] Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum MobileWebSearchOption {
        
        /// <remarks/>
        DisableHostCollapsing,
        
        /// <remarks/>
        DisableQueryAlterations,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class NewsRequest {
        
        private uint offsetField;
        
        private bool offsetFieldSpecified;
        
        private uint countField;
        
        private bool countFieldSpecified;
        
        private string locationOverrideField;
        
        private string categoryField;
        
        private NewsSortOption sortByField;
        
        private bool sortByFieldSpecified;
        
        /// <remarks/>
        public uint Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string LocationOverride {
            get {
                return this.locationOverrideField;
            }
            set {
                this.locationOverrideField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public NewsSortOption SortBy {
            get {
                return this.sortByField;
            }
            set {
                this.sortByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SortBySpecified {
            get {
                return this.sortByFieldSpecified;
            }
            set {
                this.sortByFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum NewsSortOption {
        
        /// <remarks/>
        Relevance,
        
        /// <remarks/>
        Date,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class VideoRequest {
        
        private uint offsetField;
        
        private bool offsetFieldSpecified;
        
        private uint countField;
        
        private bool countFieldSpecified;
        
        private string[] filtersField;
        
        private VideoSortOption sortByField;
        
        private bool sortByFieldSpecified;
        
        /// <remarks/>
        public uint Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] Filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
            }
        }
        
        /// <remarks/>
        public VideoSortOption SortBy {
            get {
                return this.sortByField;
            }
            set {
                this.sortByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SortBySpecified {
            get {
                return this.sortByFieldSpecified;
            }
            set {
                this.sortByFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum VideoSortOption {
        
        /// <remarks/>
        Relevance,
        
        /// <remarks/>
        Date,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class PhonebookRequest {
        
        private uint offsetField;
        
        private bool offsetFieldSpecified;
        
        private uint countField;
        
        private bool countFieldSpecified;
        
        private string fileTypeField;
        
        private PhonebookSortOption sortByField;
        
        private bool sortByFieldSpecified;
        
        private string locIdField;
        
        private string categoryField;
        
        /// <remarks/>
        public uint Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        public PhonebookSortOption SortBy {
            get {
                return this.sortByField;
            }
            set {
                this.sortByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SortBySpecified {
            get {
                return this.sortByFieldSpecified;
            }
            set {
                this.sortByFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string LocId {
            get {
                return this.locIdField;
            }
            set {
                this.locIdField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum PhonebookSortOption {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Relevance,
        
        /// <remarks/>
        Distance,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class ImageRequest {
        
        private uint offsetField;
        
        private bool offsetFieldSpecified;
        
        private uint countField;
        
        private bool countFieldSpecified;
        
        private string[] filtersField;
        
        /// <remarks/>
        public uint Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] Filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SearchCompletedEventHandler(object sender, SearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591